{
 "title": "MAAS Site Manager Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "MAAS Site Manager API Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{pebble_service=\"msm\"} |= ``"
    }
   ]
  },
  {
   "title": "DB Query Time per endpoint, method (5 min running avg)",
   "type": "timeseries",
   "description": "5 minute running average of time spent on database queries per request handler, method",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(db_queries_duration_seconds_sum[5m]))",
     "legendFormat": "raw {{handler}} ({{method}})"
    },
    {
     "expr": "sum by(handler, method) (rate(db_queries_duration_seconds_count[5m]))",
     "legendFormat": "raw {{handler}} count ({{method}})"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Database Queries per Second",
   "type": "timeseries",
   "description": "The number of database queries done per second by each handler/method",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "q/s" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(db_queries_total{handler!=\"none\"}[5m]))",
     "legendFormat": "{{handler}} ({{method}})"
    }
   ]
  },
  {
   "title": "Percentile of Time Spent on DB Queries (5 min average)",
   "type": "status-history",
   "description": "Five-minute running average of the amount of time spent on database queries for x% of requests",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(db_queries_duration_seconds_bucket{handler!=\"none\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(db_queries_duration_seconds_bucket{handler!=\"none\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(db_queries_duration_seconds_bucket{handler!=\"none\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(db_queries_duration_seconds_bucket{handler!=\"none\"}[5m])))",
     "legendFormat": "75th percentile"
    }
   ]
  }
 ]
}