name: Release Charm to Edge and Publish Libraries

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: skatsaounis/observability/.github/workflows/charm-release.yaml@fix-tests
    secrets: inherit
