name: Release Charm to Edge and Publish Libraries

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release MAAS Site Manager charm to edge
    uses: canonical/observability/.github/workflows/charm-release.yaml@v0
    secrets: inherit
    with:
      juju-channel: 3.6/stable
      charmcraft-channel: latest/stable
      provider: microk8s
