name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lib:
    name: Check libraries
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v3
        with:
          fetch-depth: 0

      - name: Fetch charm libraries
        run: |
          sudo snap install charmcraft --classic --channel latest/stable
          charmcraft fetch-lib

      - name: Create a PR for local changes
        uses: peter-evans/create-pull-request@v6 # v6
        id: cpr
        with:
          commit-message: "chore: update charm libraries"
          committer: "Github Actions <github-actions@github.com>"
          author: "Github Actions <github-actions@github.com>"
          title: "Update charm libraries"
          body: |
            Automated action to fetch latest version of charm libraries. The branch of this PR
            will be wiped during the next check. Unless you really know what you're doing, you
            most likely don't want to push any commits to this branch.
          branch: "chore/auto-libs"
          delete-branch: true
