name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  update-libs:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@v0
    secrets: inherit
    with:
      commit-username: maas-lander
      commit-email: 115650013+maas-lander@users.noreply.github.com
